const picAnswers = [
  ["butter", "fly"],
  ["back", "fire"],
  ["baby", "sit"],
  ["foot", "ball"],
  ["work", "sheet"],
  ["after", "glow"],
  ["air", "craft"],
  ["bee", "side", "beside"],
  ["knee", "body", "anybody"],
  ["arm", "pit"],
  ["arrow", "head"],
  ["back", "bone"],
  ["black", "out"],
  ["bell", "hop"],
  ["author", "ship"],
  ["blue", "print"],
  ["bank", "roll"],
  ["book", "case"],
  ["bed", "rock"],
  ["jack", "pot"],
  ["cob", "web"],
  ["straw", "berry"],
  ["dough", "boy"],
  ["hog", "wash"],
  ["piece", "meal"],
  ["bull", "doze"],
  ["smart", "phone"],
  ["stock", "broker"],
  ["snow", "man"],
  ["base", "ball"],
  ["world", "wide"],
  ["candle", "stick"],
  ["tree", "house"],
  ["dare", "devil"],
  ["dash", "board"],
  ["data", "base"],
  ["never", "mind"],
  ["sand", "witch", "sandwich"],
  ["rail", "road"],
  ["sea", "shell"],
  ["ear", "ring"],
  ["star", "art", "start"],
  ["key", "board"],
  ["jump", "rope"],
  ["e", "mail"],
  ["pen", "knee", "penny"],
  ["ill", "eagle", "illegal"],
  ["jay", "walk"],
  ["pee", "pole", "people"],
  ["net", "work"],
  ["knight", "mare", "nightmare"],
  ["fry", "day", "friday"],
  ["hair", "cut"],
  ["pine", "cone"],
  ["part", "tea", "party"],
  ["vine", "yard"],
  ["d", "fense", "defense"],
  ["treat", "tee", "treaty"],
  ["t", "shirt"],
  ["sky", "line"],
  ["sea", "sun", "season"],
  ["bag", "pipe"],
  ["wrist", "watch"],
  ["pro", "gram"],
  ["star", "fish"],
  ["tooth", "brush"],
  ["tripod", "unicycle", "tricycle"],
  ["tennis", "ball"],
  ["water", "melon"],
  ["sodium", "chloride", "salt"],
  ["blow", "fish"],
  ["kit", "ten"],
  ["scare", "crow"],
  ["honey", "dew"],
  ["pub", "lick"],
  ["flag", "pole"],
  ["axe", "cent", "accent"],
  ["alt", "tar", "altar"],
  ["meat", "ball"],
  ["post", "card"],
  ["soy", "sauce"],
  ["tip", "toe"],
  ["hole", "sail", "wholesale"],
  ["glow", "worm"],
  ["fire", "fly"],
  ["best", "buy"],
  ["wire", "ring", "wiring"],
  ["explode", "sieve", "explosive"],
  ["grape", "fruit"],
  ["break", "dance"],
  ["slow", "dancing", "slowdance"],
  ["pig", "pen"],
  ["pair", "ant", "parent"],
  ["pony", "tail"],
  ["pepper", "mints", "peppermint"],
  ["bill", "board"],
  ["wall", "flower"],
  ["cross", "bow"],
  ["nose", "bleed"],
  ["word", "pic"]
];
